import { ROUTES } from "@/constants/routes";

export const routeMap = {
  // Public Routes
  HOME: { path: ROUTES.HOME },
  LOGIN: { path: ROUTES.LOGIN },
  REGISTER: { path: ROUTES.REGISTER },
  FORGOT_PASSWORD: { path: ROUTES.FORGOT_PASSWORD },
  RESET_PASSWORD: { path: ROUTES.RESET_PASSWORD },
  VERIFY_EMAIL: { path: ROUTES.VERIFY_EMAIL },
  VERIFY_OTP: { path: ROUTES.VERIFY_OTP },
  HOW_IT_WORKS: { path: ROUTES.HOW_IT_WORKS },
  ABOUT: { path: ROUTES.ABOUT },
  SEARCH: { path: ROUTES.SEARCH },
  PROVIDER_PROFILE: { path: ROUTES.PROVIDER_PROFILE },
  BOOKING_CLEANING: { path: ROUTES.BOOKING_CLEANING },
  BOOKING_CARWASH: { path: ROUTES.BOOKING_CARWASH },
  BOOK_PROVIDER: { path: ROUTES.BOOK_PROVIDER },
  BOOKING_DETAIL: { path: ROUTES.BOOKING_DETAIL },
  CHECKOUT: { path: ROUTES.CHECKOUT },
  RATING: { path: ROUTES.RATING },

  // Admin Routes
  ADMIN_DASHBOARD: { path: ROUTES.ADMIN_DASHBOARD },
  ADMIN_CATEGORIES: { path: ROUTES.ADMIN_CATEGORIES },
  ADMIN_SERVICES: { path: ROUTES.ADMIN_SERVICES },
  ADMIN_PROVIDERS: { path: ROUTES.ADMIN_PROVIDERS },
  ADMIN_PROVIDER_DETAIL: { path: ROUTES.ADMIN_PROVIDER_DETAIL },
  ADMIN_CUSTOMERS: { path: ROUTES.ADMIN_CUSTOMERS },
  ADMIN_ORDERS: { path: ROUTES.ADMIN_ORDERS },
  ADMIN_DISPUTES: { path: ROUTES.ADMIN_DISPUTES },
  ADMIN_DISPUTE_DETAIL: { path: ROUTES.ADMIN_DISPUTE_DETAIL },
  ADMIN_REVIEWS: { path: ROUTES.ADMIN_REVIEWS },
  ADMIN_SPONSORED: { path: ROUTES.ADMIN_SPONSORED },
  ADMIN_COINS: { path: ROUTES.ADMIN_COINS },
  ADMIN_FEATURED: { path: ROUTES.ADMIN_FEATURED },
  ADMIN_MESSAGES_DETAIL: { path: ROUTES.ADMIN_MESSAGES_DETAIL },
  ADMIN_PROFILE: { path: ROUTES.ADMIN_PROFILE },
  ADMIN_SUPPORT_AGENTS: { path: ROUTES.ADMIN_SUPPORT_AGENTS },
  ADMIN_SETTINGS: { path: ROUTES.ADMIN_SETTINGS },

  // Support Routes
  SUPPORT_DASHBOARD: { path: ROUTES.SUPPORT_DASHBOARD },
  SUPPORT_MESSAGES: { path: ROUTES.SUPPORT_MESSAGES },
  SUPPORT_PROVIDERS: { path: ROUTES.SUPPORT_PROVIDERS },
  SUPPORT_REFUNDS: { path: ROUTES.SUPPORT_REFUNDS },
  SUPPORT_DISPUTES: { path: ROUTES.SUPPORT_DISPUTES },
  SUPPORT_DISPUTE_DETAIL: { path: ROUTES.SUPPORT_DISPUTE_DETAIL },
  SUPPORT_SETTINGS: { path: ROUTES.SUPPORT_SETTINGS },

  // Customer Routes
  CUSTOMER_DASHBOARD: { path: ROUTES.CUSTOMER_DASHBOARD },
  CUSTOMER_ORDERS: { path: ROUTES.CUSTOMER_ORDERS },
  CUSTOMER_ORDER_DETAIL: { path: ROUTES.CUSTOMER_ORDER_DETAIL },
  CUSTOMER_BOOKINGS_DETAIL: { path: ROUTES.CUSTOMER_BOOKINGS_DETAIL },
  CUSTOMER_REPORT_ISSUE: { path: ROUTES.CUSTOMER_REPORT_ISSUE },
  CUSTOMER_MESSAGES: { path: ROUTES.CUSTOMER_MESSAGES },
  CUSTOMER_PROFILE: { path: ROUTES.CUSTOMER_PROFILE },
  CUSTOMER_PROJECTS: { path: ROUTES.CUSTOMER_PROJECTS },
  PROJECT_DETAIL: { path: ROUTES.PROJECT_DETAIL },
  APPOINTMENTS: { path: ROUTES.APPOINTMENTS },
  CUSTOMER_BOOKINGS: { path: ROUTES.CUSTOMER_BOOKINGS },
  CUSTOMER_REVIEWS: { path: ROUTES.CUSTOMER_REVIEWS },

  // Provider Routes
  PROVIDER_DASHBOARD: { path: ROUTES.PROVIDER_DASHBOARD },
  PROVIDER_OPPORTUNITIES: { path: ROUTES.PROVIDER_OPPORTUNITIES },
  PROVIDER_JOBS: { path: ROUTES.PROVIDER_JOBS },
  PROVIDER_ORDERS: { path: ROUTES.PROVIDER_ORDERS },
  PROVIDER_ORDER_DETAIL: { path: ROUTES.PROVIDER_ORDER_DETAIL },
  PROVIDER_PRICING: { path: ROUTES.PROVIDER_PRICING },
  PROVIDER_SERVICES_PRICING: { path: ROUTES.PROVIDER_SERVICES_PRICING },
  PROVIDER_AVAILABILITY: { path: ROUTES.PROVIDER_AVAILABILITY },
  PROVIDER_EARNINGS: { path: ROUTES.PROVIDER_EARNINGS },
  PROVIDER_FEATURED: { path: ROUTES.PROVIDER_FEATURED },
  PROVIDER_PROFILE_SETTINGS: { path: ROUTES.PROVIDER_PROFILE_SETTINGS },
  PROVIDER_ONBOARDING: { path: ROUTES.PROVIDER_ONBOARDING },

  // 404
  NOT_FOUND: { path: ROUTES.NOT_FOUND },
} as const;

export default routeMap;
