export const ROUTES = {
  // Public
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_OTP: "/verify-otp",
  HOW_IT_WORKS: "/how-it-works",
  ABOUT: "/about",
  SEARCH: "/search",
  PROVIDER_PROFILE: "/provider/:id",
  BOOKING_CLEANING: "/booking/cleaning",
  BOOKING_CARWASH: "/booking/carwash",
  BOOK_PROVIDER: "/book/:providerId",
  BOOKING_DETAIL: "/booking/:id",
  CHECKOUT: "/checkout",
  RATING: "/rating/:id",

  // Customer Protected
  CUSTOMER_DASHBOARD: "/dashboard",
  CUSTOMER_ORDERS: "/orders",
  CUSTOMER_ORDER_DETAIL: "/order/:id",
  CUSTOMER_BOOKINGS_DETAIL: "/customer/bookings/:id",
  CUSTOMER_REPORT_ISSUE: "/report-issue/:id",
  CUSTOMER_MESSAGES: "/messages",
  CUSTOMER_PROFILE: "/profile",
  CUSTOMER_PROJECTS: "/projects",
  PROJECT_DETAIL: "/projects/:id",
  APPOINTMENTS: "/appointments",
  CUSTOMER_BOOKINGS: "/customer/bookings",
  CUSTOMER_REVIEWS: "/customer/reviews",

  // Provider Protected
  PROVIDER_DASHBOARD: "/provider/dashboard",
  PROVIDER_OPPORTUNITIES: "/provider/opportunities",
  PROVIDER_JOBS: "/provider/jobs",
  PROVIDER_ORDERS: "/provider/orders",
  PROVIDER_ORDER_DETAIL: "/provider/order/:id",
  PROVIDER_PRICING: "/provider/pricing",
  PROVIDER_SERVICES_PRICING: "/provider/services-pricing",
  PROVIDER_AVAILABILITY: "/provider/availability",
  PROVIDER_EARNINGS: "/provider/earnings",
  PROVIDER_FEATURED: "/provider/featured",
  PROVIDER_PROFILE_SETTINGS: "/provider/profile",
  PROVIDER_CUSTOM_REQUEST_DETAIL: "/provider/custom-requests/:id",
  PROVIDER_ONBOARDING: "/provider/onboarding",

  // Admin Protected
  ADMIN_DASHBOARD: "/admin",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_SERVICES: "/admin/services",
  ADMIN_PROVIDERS: "/admin/providers",
  ADMIN_PROVIDER_DETAIL: "/admin/providers/:id",
  ADMIN_CUSTOMERS: "/admin/customers",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_DISPUTES: "/admin/disputes",
  ADMIN_DISPUTE_DETAIL: "/admin/disputes/:id",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_SPONSORED: "/admin/sponsored",
  ADMIN_COINS: "/admin/coins",
  ADMIN_FEATURED: "/admin/featured",
  ADMIN_MESSAGES_DETAIL: "/admin/messages/:id",
  ADMIN_PROFILE: "/admin/profile",
  ADMIN_SUPPORT_AGENTS: "/admin/support-agents",
  ADMIN_SETTINGS: "/admin/settings",

  // Support Protected
  SUPPORT_DASHBOARD: "/support-dashboard",
  SUPPORT_MESSAGES: "/support-dashboard/messages",
  SUPPORT_PROVIDERS: "/support-dashboard/providers",
  SUPPORT_REFUNDS: "/support-dashboard/refunds",
  SUPPORT_DISPUTES: "/support-dashboard/disputes",
  SUPPORT_DISPUTE_DETAIL: "/support-dashboard/disputes/:id",
  SUPPORT_SETTINGS: "/support-dashboard/settings",

  // Fallback
  NOT_FOUND: "*",
} as const;
